### ISSUE TITLE
Upon visiting the oauth url, astro server gives a 404 error

### ISSUE THREAD

**Issue by Tdnshah** [dorukgezici/astro-decap-cms-oauth#1]
I was trying to use this to add authentication for my astro site recently upgraded to latest version of astro 3.

When I click on login with github button provided by Decap a pop openup with below url

`https://{mydomain}/oauth/?provider=github&site_id={mydomain name}&scope=repo` 
and this leads to a 404 error

<img width="1214" alt="Screenshot 2023-09-15 at 2 09 22 PM" src="https://github.com/dorukgezici/astro-decap-cms-oauth/assets/13272752/7fba09f3-9496-4dc1-aa15-9dd05e0531d0">

Anyidea what is causing this ?

**Comment by AlbanCrepel** [comment]
I have the exact same error

**Comment by dorukgezici** [comment]
Are you sure you have set up Astro in SSR mode? Also have the env variables set?
There might be something wrong with your Decap CMS config file as well, I can check if you can share.
