### ISSUE TITLE
Undefined variables on build (also happens with dev environment)

### ISSUE THREAD

**Issue by tatsupro** [dorukgezici/astro-decap-cms-oauth#16]
Hi Gezici, I have some trouble when deploying Decap. The `/admin` route is still on but when I click "Login with Github" is return this url `https://github.com/login/oauth/authorize?client_id=undefined&scope=repo,user`.

Maybe the package have some trouble when reading the env or I missing something when setting up? Thanks.

Service: Cloudflare Pages
Package version: 0.2.9 and 0.3.0

**Comment by legendary-jld** [comment]
Having the same issue. ENV vars are setup, also using Cloudflare Pages for hosting as well.

**Comment by dorukgezici** [comment]
Sorry for the late reply, the config file that URL is coming from is basically this:
 ```
export const clientId = process.env.OAUTH_GITHUB_CLIENT_ID;
export const clientSecret = process.env.OAUTH_GITHUB_CLIENT_SECRET;

export const authUrl = `https://github.com/login/oauth/authorize?client_id=${clientId}&scope=repo,user`;
export const tokenUrl = "https://github.com/login/oauth/access_token";
```

It sounds like the runtime in Cloudflare Pages can't read the env vars via `process.env`. I have updated it with `import.meta.env`, but not sure if it will fix it for you and I don't use Cloudflare Pages so couldn't test.
