### ISSUE TITLE
undefined env in cloudfare 

### ISSUE THREAD

**Issue by avevotsira** [dorukgezici/astro-decap-cms-oauth#37]
cloudfare page/worker will have undefined env. 

related to https://github.com/dorukgezici/astro-decap-cms-oauth/issues/16

workaround to this would have  to use the :

https://docs.astro.build/en/reference/configuration-reference/#experimentalenv

or

https://docs.astro.build/en/guides/integrations-guide/cloudflare/#cloudflare-runtime

**Comment by dorukgezici** [comment]
I have switched to using experimental `astro:env` starting with this [release](https://github.com/dorukgezici/astro-decap-cms-oauth/releases/tag/v0.4.1)

Thanks for the input!
