### ISSUE TITLE
Getting errors when going to /admin

### ISSUE THREAD

**Issue by aristocratious** [dorukgezici/astro-decap-cms-oauth#9]
Hi, I am getting these errors. Maybe I am missing something in the instructions? Thanks.

Error loading the CMS configuration
Config Errors:
config must have required property 'media_folder'
config must have required property 'media_library'
config must match a schema in anyOf
config must have required property 'collections'
Check your config.yml file.

If it makes sense I can send a note to the Decap team to include a template for this Oauth (without locking to Netlify option) on this page https://decapcms.org/docs/start-with-a-template/

**Comment by aristocratious** [comment]
Oh, I realized a mistake. Also related to the proposed change to the readme I just made. Sorry for the confusion. I just moved the pre-created config.yml (instead of creating a new). However I kept the name: git-gateway instead of using github.

**Comment by dorukgezici** [comment]
Closing the issue in that case 👍
